### PR TITLE
Set Stars for all github repositories

### PR DESCRIPTION
**Pull request by SamProf**
@AdrienTorris and @chrissainty ,
Just for test I have update all stars for all repositories. What you think about it?

### CODE REVIEW

**Comment by AdrienTorris** [comment]
Hi SamProf!
How are you?

Thank's for this PR, it's awesome.

Also, like I told on another PR (#155), I'm wondering if it's a good think to display all the stars numbers. One of the goal is to draw attention on the most followed items, I'm not sure that is relevant to display that a project has 1 or 2 stars. Also, it will be more difficult to maintain.

My point is that we have to decide to a minimum level of star to display it. I had 10 in mind, but we can discuss it.
What do you think?

**Comment by stavroskasidis** [comment]
Could something like this be used for maintainability ?

https://github.com/ddavison/github-badges

**Comment by AdrienTorris** [comment]
Hi stavroskasidis!

GitHub badges looks perfect! I will dig this but thank you very much for this!

**Comment by AdrienTorris** [comment]
Test: http://githubbadges.com/star.svg?user=adrientorris&repo=awesome-blazor&style=flat

**Comment by chrissainty** [comment]
@SamProf @AdrienTorris Sorry I’m a bit late to the party, busy upgrading packages for preview 7! 

The stars look awesome! I do agree with Adrien that we should have a minimum number, 10 sounds good to me. Maybe this should adjust over time as well? As Blazor becomes more main stream and start counts get much higher?

GitHub badges seems the best way to go from a maintainability standpoint as well.

**Comment by stsrki** [comment]
I think adding stars on all projects is not really good. The idea with stars was to draw attention to the most followed and best projects. With all stars visible it's a mess to see anything. Also maintaining them will be a mess, even for just a few of them. 

#159 is a good way I think

**Comment by SamProf** [comment]
@AdrienTorris , @chrissainty 

It was just first test.
So, I have few ideas to improve my idea.
- Yes, we can don't display stars for less nMin (10) stars.
- Display few star
-- :star::star: or :star2: for reposities  >=nMax (100)
-- :star: for repositories >=nMin <nMax
-- hide for <nMin
- Sorting inside group by stars count.

What you think about this ideas?

**Comment by ctrl-alt-d** [comment]
I like the idea to have stars on all repos. I like to see my modest five stars next to my repo. Also, I think, top repos should have better visibility https://github.com/AdrienTorris/awesome-blazor/issues/140#issuecomment-507050304:

>Create a visibility strategy to mote to "relegated to second place" non interesting projects (secondary list/page) and highlight interested projects ( Ex: top on each category, max 10 ). Also, one interested project can participate in several categories. I think it is important to do not sort the categories alphabetically but for interest, and, also, do not sort projects into categories alphabetically, use our own criteria (stars, quality, demo, open source, maintenance, ... ). For example, all people are looking for components, then, put components at top. Maybe, at top, an special category like "mandatoy" or "indispensable" with max 5 projects.

I also like the @SamProf  idea about to have different kind of stars.

**Pull request merged**
