### PR TITLE
Add link to Stl.Fusion to "Others" section

### PR DESCRIPTION
**Pull request by alexyakunin**

### CODE REVIEW

**Comment by alexyakunin** [comment]
Please approve this pull request...

**Comment by AdrienTorris** [comment]
Hi,

It seems that this repository is already mentioned, a few lines upper. Isn't it?

Kind regards,

**Comment by alexyakunin** [comment]
@AdrienTorris no, it's not. Maybe you're referring to SyncFusion's Blazor components? It's a totally different library.

**Comment by alexyakunin** [comment]
Please search for "Stl.Fusion".

**Comment by AdrienTorris** [comment]
This is what I see:
stlfusionpr

**Comment by AdrienTorris** [comment]
Is this the link you want to add? https://github.com/servicetitan/Stl.Fusion.Samples

**Comment by alexyakunin** [comment]
Oh I am awfully sorry, @AdrienTorris  - yes, I wanted to add a link to https://github.com/servicetitan/Stl.Fusion ; let me fix it.

**Comment by alexyakunin** [comment]
@AdrienTorris I ended up creating another, clean pull request for this: https://github.com/AdrienTorris/awesome-blazor/pull/378

**Comment by alexyakunin** [comment]
This one should be closed.

**Pull request closed without merging**
